<a href="https://colab.research.google.com/github/arpit-parejiya01/ML/blob/main/ML%20MODUAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy declaration**

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
print(np.__version__)

1.23.5


In [5]:
print(arr.dtype)
print(arr.shape)

int64
(5,)


In [6]:
arr1 = np.array([[1.2,1.2,1.3],[2.1,2.2,2.3]])
print(arr1)
print(arr1.dtype)
print(arr1.shape)

[[1.2 1.2 1.3]
 [2.1 2.2 2.3]]
float64
(2, 3)


In [7]:
lst = [[1,2,3,4],[5,6,7,8],[1.1,1.2,1.3,1.4],[2.1,2.2,2.3,2.4]]
arr2 = np.array(lst)
print(arr2)
print(arr2.dtype)
print(arr2.shape)

[[1.  2.  3.  4. ]
 [5.  6.  7.  8. ]
 [1.1 1.2 1.3 1.4]
 [2.1 2.2 2.3 2.4]]
float64
(4, 4)


**Indexing and slicing**

In [10]:
print(arr2[0])
print(arr2[0,3])

[1. 2. 3. 4.]
4.0


In [13]:
print(arr2[1,:])
print(arr2[:,0])
print(arr2[2,1:3])

[5. 6. 7. 8.]
[1.  5.  1.1 2.1]
[1.2 1.3]


x = arr2[:,0:2]
y = arr2[:,-1]
print(x)
print(y)

In [2]:
import numpy as np
lst = [[1,2,3],[11,12,13],[21,22,23],[31,32,33]]
arr = np.array(lst)
print(arr)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [6]:
x = arr[:,0]
y = arr[:,-1]
print(x)
print(y)

[ 1 11 21 31]
[ 3 13 23 33]


In [10]:
print(arr[arr % 7 == 0])
print(arr[arr > 10])

[21]
[11 12 13 21 22 23 31 32 33]


In [11]:
for x in arr :
  print(x)

[1 2 3]
[11 12 13]
[21 22 23]
[31 32 33]


In [12]:
for x in arr :
  for y in x:
    print(y)

1
2
3
11
12
13
21
22
23
31
32
33


In [18]:
ans = np.sum(arr)
print("sum is :- ",ans)
ans = np.min(arr)
print("min is :- ",ans)
ans = np.max(arr)
print("max is :- ",ans)
ans = np.mean(arr)
print("mean is :- ",ans)
ans = np.median(arr)
print("median is :- ",ans)
ans = np.std(arr)
print("stand deviation :- ",ans)


sum is :-  204
min is :-  1
max is :-  33
mean is :-  17.0
median is :-  17.0
stand deviation :-  11.210114480533491


In [5]:
import numpy as np
lst = [[1,2,3],[11,12,13],[21,22,23],[31,32,33]]
arr = np.array(lst)
print(arr)
ans = np.sum(arr,axis=0)
print("sum of column :- ",ans)
ans = np.sum(arr,axis=1)
print("sum of rows :- ",ans)
ans = np.mean(arr,axis=0)
print("mean of column :- ",ans)
ans = np.mean(arr,axis=1)
print("mean of rows :- ",ans)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
sum of column :-  [64 68 72]
sum of rows :-  [ 6 36 66 96]
mean of column :-  [16. 17. 18.]
mean of rows :-  [ 2. 12. 22. 32.]
